### ISSUE TITLE
VG2012 Json

### ISSUE THREAD

**Issue by jweisbaum** [kbsali/regadata#10]
Hey Kevin, do you have the full json for all VG2012 points laying around anywhere? Thanks.

**Comment by kbsali** [comment]
Hey @jweisbaum ,

I'd have to find a backup of the mongodb collection and dump it to json.
Hope I can find that!

**Comment by jweisbaum** [comment]
If it's easier and you can find it you can just send me a copy of your
mongodb :). I'm putting together a big archive of old sailing data. Some is
really frustratingly hard to find.

**Comment by kbsali** [comment]
discussed per email.
