### ISSUE TITLE
Links don't work for downloads and Google Maps

### ISSUE THREAD

**Issue by Herman031** [kbsali/regadata#2]
Hi Kevin,

Just a heads up that when I try to download a file at the bottom of the page http://vg2016.regadata.org/en/reports/latest

both the links  to:

vg2016.kmz and 
Official Map

Return an server error according to Chrome (latest version) on Windows 10 (latest version) "Whoops, looks like something went wrong."

Also, the link to Google Maps returns an error screen; "Sorry, the page you are looking for could not be found."

As I use the kmz file to import boat positions for weather routing analysis, I would be very happy if I could download again the KMZ files.

With kind regards,

Herman

**Comment by kbsali** [comment]
Hi @Herman031,

thanks a lot for reporting those issues (and sorry for answering so late!).
I've fixed both issues!

Regards,
Kevin.

**Comment by kbsali** [comment]
I just gave the kmz file a try on my computer and it looks like it does not quite work as expected! I'll try to have a look into it asap!

**Comment by Herman031** [comment]
Hi Kevin,

Merci bien!

Herman

2016-12-08 14:12 GMT+01:00 Kevin Saliou <notifications@github.com>:
