### ISSUE TITLE
VG2016 - Read official tracks files ?

### ISSUE THREAD

**Issue by steph-ben** [kbsali/regadata#3]
Merci pour ce projet, j'étais justement en train de réfléchir à faire la même chose !

Par pur curiosité, concernant les données sur VG2016, avais-tu essayé de regarder les tracks utilisées par l'appli de cartographie officielle ?
Par exemple: http://tracking2016.vendeeglobe.org/gv5ip0/resources/tracker.tracks.hwz?v=20161204210008
On tombe sur un fichier binaire, je n'ai aucune idée de comment le décoder ...

**Comment by kbsali** [comment]
Hello,

j'avais regardé oui, mais c'est trop de données pour ce que je veux représenter!
A mon avis ce n'est intéressant que si tu veux faire de la carto (je pense que c'est les données qu'utilise *volodia* pour http://volodiaja.net/Tracking/ ).
Sinon ce "binaire" n'est en fait qu'un json zippé avec tous les points relevés : 
```
$ file ~/Downloads/tracker.tracks.hwz 
/home/kevin/Downloads/tracker.tracks.hwz: Zip archive data, at least v2.0 to extract

$ unzip ~/Downloads/tracker.tracks.hwz
Archive:  /home/kevin/Downloads/tracker.tracks.hwz
  inflating: tracker.tracks.data     

$ head ~/Downloads/tracker.tracks.data 
{"tracks":[
        {
                "id":1,
                "loc":[
                        [1478433720,4642402,-178505],[240,358,-255],[360,-890,-2190],[360,-690,-2330],[360,-690,-2430],[360,-670,-2580],[360,-700,-2700],[360,-590,-2550],[360,-450,-2360],[360,-560,-2600],[360,-620,-2770],[360,-610,-2600],[360,-640,-2790],[360,-570,-2520],[360,-620,-2650],[360,-570,-2550],[360,-580,-2500],[360,-570,-2490],[360,-560,-2360],[360,-570,-2480],[360,-580,-2450],[360,-560,-2500],[360,-600,-2650],[360,-580,-2500],[360,-640,-2400],[360,-750,-2470],[360,-730,-2300]
```

En regardant vite fait je pense que c'est [time, lat, long] dans chaque élément, que le tout 1er représente l'heure du 1er pointage, et ensuite c'est le nombre de seconde entre chaque pointage... ou pas?

**Comment by steph-ben** [comment]
Ah oui merci bien vu ! C'est exactement ce que je cherchais.

A vrai dire, j'ai confondu avec ces fichiers, sur lesquels là pour le coup semblent un peu plus difficile à décoder
http://tracking2016.vendeeglobe.org/x6hz61/datas/positions/2016-12-02-08-00-00_20161202090001.bin

**Comment by kbsali** [comment]
Oui, là je ne sais pas! :) Mais peut être que Volodia voudra bien t'informer (via twitter)?
