### ISSUE TITLE
position data gone

### ISSUE THREAD

**Issue by Herman031** [kbsali/regadata#6]
Dear Kevin,

In the latest schedule the position data is empty. This could have to do with that Geoville has encrypted their VG2016 data. Or maybe something else. 

EDIT: VG2016 has retracted boat positions from their excel schedules :(

With kind regards,

Herman

**Comment by kbsali** [comment]
yep, since today noon (https://twitter.com/VGRaceData/status/808674795604901888)... :-1: 
Nothing we can do...

**Comment by kbsali** [comment]
and yes, I also believe it is related to Geovoile encrypting its data...
