### ISSUE TITLE
issue with KML file Alex Thomson

### ISSUE THREAD

**Issue by Herman031** [kbsali/regadata#7]
Hi Kevin,

Just a note to let you know that the boat position data for AT seems to be missing in the KML files. Both the combined boat data file and the individual boat data file. I use these KML files in combination with EUMETSAT images to assess the doldrum situation for the 2 leaders in Google Earth. 

Cheers,

Herman

**Comment by kbsali** [comment]
I believe it is there, but its trace seems to be invisible.

**Comment by kbsali** [comment]
could you give it another try, it should be fixed now.

Thanks for reporting those issues! :)

**Comment by Herman031** [comment]
Hi Kevin, the track is visible now, thanks again!

2017-01-15 21:44 GMT+01:00 Kevin Saliou <notifications@github.com>:
