### ISSUE TITLE
New data format

### ISSUE THREAD

**Issue by Herman031** [kbsali/regadata#8]
Hi Kevin,

Forss at Sailing Anarchy noted that the VG 2016 positions data format has changed, you should probably check this out and adjust the conversion because since 22:00 last night, no more updates are posted on your site. I hope you can find time to fix this, as I use your Regadata files a lot and the finish of the race is coming closer - Jan. 19th I naviguessed yesterday.  

Cheers and thanks for all your great work!

Herman

**Comment by kbsali** [comment]
Hi Herman,

thanks for notifying, i realised this this morning and will try to fix it asap!

**Comment by kbsali** [comment]
fixed.
For some reason they removed an invisible column...

**Comment by Herman031** [comment]
Thanks for the quick action. The issue with the Alex Thomson data can't be
solved?

2017-01-12 22:40 GMT+01:00 Kevin Saliou <notifications@github.com>:
