### ISSUE TITLE
Glitch in data

### ISSUE THREAD

**Issue by Herman031** [kbsali/regadata#9]
Hi Kevin,

In the boat comparison graphs there seems to be a data glitch. For all boats afaik. Issue is that the value of that data glitch is so high, that the valid data can't be distinguished. I've added a screenshot.

![schermafdruk 2017-01-23 09 57 40](https://cloud.githubusercontent.com/assets/9025590/22197554/c8bedd9c-e152-11e6-9d80-2abcd03e43ff.png)

**Comment by kbsali** [comment]
Hi @Herman031 ,

sorry for the 3 years delay before giving you an answer... Indeed there were issue in the last editions... Not sure i'll have time & motivation to rerun it for the 2020 edition ! If i do, i'll make sure this is fixed! :sweat_smile: 
thanks!
